# Optimization hyperparameter

In [1]:
# Import dependencies 
import pandas as pd
import os
import matplotlib.pyplot as plt

In [10]:
# import dependencies
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# Import encoded datafram
encoded_df3 = pd.read_csv('encoded_df3.csv')
encoded_df3

state_beer              style  availability   abv  types  taste
0               36  German Hefeweizen             2   5.0      4   4.50
1               36  German Hefeweizen             6   5.6      2   4.50
2               43  German Hefeweizen             6   5.4      1   4.00
3               37  German Hefeweizen             4   5.0     10   4.25
4               46  German Hefeweizen             2   4.5      3   4.00
...            ...                ...           ...   ...    ...    ...
443995           4              Stout             6   5.8      3   4.50
443996          10              Stout             2   8.0      2   3.50
443997           4              Stout             2  11.0     10   5.00
443998          22              Stout             2  13.1      5   4.75
443999          15              Stout             6  10.0      1   4.50

[444000 rows x 6 columns]

In [3]:
#encode string values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_df4 = encoded_df3.copy()
encoded_df4['style'] = le.fit_transform(encoded_df4['style'])
encoded_df4

state_beer  style  availability   abv  types  taste
0               36     18             2   5.0      4   4.50
1               36     18             6   5.6      2   4.50
2               43     18             6   5.4      1   4.00
3               37     18             4   5.0     10   4.25
4               46     18             2   4.5      3   4.00
...            ...    ...           ...   ...    ...    ...
443995           4     36             6   5.8      3   4.50
443996          10     36             2   8.0      2   3.50
443997           4     36             2  11.0     10   5.00
443998          22     36             2  13.1      5   4.75
443999          15     36             6  10.0      1   4.50

[444000 rows x 6 columns]

In [40]:
# Define the target set
y = encoded_df3["style"].values
y

array(['German Hefeweizen', 'German Hefeweizen', 'German Hefeweizen', ...,
       'Stout', 'Stout', 'Stout'], dtype=object)

In [18]:
#define the features set
X = encoded_df3.copy()
X = X.drop(columns =["style"])
X

state_beer  availability   abv  types  taste
0               36             2   5.0      4   4.50
1               36             6   5.6      2   4.50
2               43             6   5.4      1   4.00
3               37             4   5.0     10   4.25
4               46             2   4.5      3   4.00
...            ...           ...   ...    ...    ...
443995           4             6   5.8      3   4.50
443996          10             2   8.0      2   3.50
443997           4             2  11.0     10   5.00
443998          22             2  13.1      5   4.75
443999          15             6  10.0      1   4.50

[444000 rows x 5 columns]

In [41]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [42]:
# Create a StandardScaler instance
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [43]:
# Create a random forest classifier
xgb_model = XGBClassifier()
# fit the model
xgb_model = xgb_model.fit(X_train_scaled, y_train)

/Users/alexzzf/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[09:43:51] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [44]:
# make predictions for test data
predictions = xgb_model.predict(X_test_scaled)

In [45]:
#calculate matrix and accuracy score
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(cm)
acc_score = accuracy_score(y_test, predictions)


In [46]:
display(cm_df)

0     1     2     3     4     5     6     7     8     9   ...    30  \
0   2675     1    19     3     3    19    31    74    21     7  ...    19   
1      2  2907    10   207    74     0     0     0     3    41  ...    14   
2      4     1  2947    12    41     3     6     2     2    33  ...    28   
3      5    89     2  3157    47     3     0     0     2     5  ...     6   
4     12    50    34    59  2996     4     1     1     8    37  ...    28   
5     55     4    13     2    23  2319    47    66    79     5  ...    18   
6     34     0     4     0     0    14  2950    37     9     3  ...     6   
7     75     0    30     0     4   113    99  2145    50    32  ...    21   
8     77    15    66    17    17    27    38    62  2087    28  ...    80   
9     11    66   106    74   175    37    64    36    33  1985  ...    56   
10    50     0    13     0     5    10    34    18    30     3  ...    71   
11     0    51    22    28    64     9     2     2    24    22  ...     1   
12    52     2   105     5    55    37    77    60    41    69  ...    54   
13     7     2    69     0    11     2    20     5     7    11  ...     9   
14    38     3    31     5    29    46    77    88    20    31  ...    23   
15    31     1    19     0     4    11    13    58    39    10  ...    18   
16     9     0    16     0     6     8     0     4     4     6  ...    14   
17     8    11    52    12    62     2     0     6     7    20  ...    10   
18    50     0     6     0     1    93    38   120    40     6  ...    41   
19    33     0     7     0     0    20    65    70    10     3  ...    26   
20    88     0     0     0     0    84    62   108    33     4  ...    15   
21     6     1    20     2    11     3     1     7     3     3  ...    15   
22    11     0     3     0     0     7     7     2    27     4  ...     8   
23    21     1    32     1     3    22    34    33    24     5  ...    12   
24    13     4    27     6     7    18    14    39    15    20  ...     5   
25   110     8    18     0     2    58    52    62    58    15  ...    14   
26    21     0     7     5     0    29   366    59    19     1  ...    13   
27    42   121   144    23    90    64    59    41    27    45  ...    35   
28    29    42   134    21   158    47    45    61    58   108  ...   138   
29    79     5    26     1    28    37    60    84    58    14  ...    31   
30    66    36    61    33    74    32    12    37    75    47  ...  1941   
31     6     8    10     1     7     1     5    12     3     3  ...     6   
32    88    23    49     9    40    66    16    84    96    64  ...    91   
33    35    16    20    12    35    28    25    11    19    18  ...    35   
34     4    41    72    40   123     2     2     1     7    56  ...    24   
35    13    11    27     0     8     5    29    25    16     5  ...    38   
36    22   181    42    99   123    14    14    17    34    84  ...    99   
37     5   103    37    60    88     0     0     0    12    22  ...    34   
38    24    28    74    17    57    30   145    30    19    61  ...    37   
39     6    14     7     1     8     5     6     5     7    12  ...    10   

      31    32    33    34    35    36    37    38    39  
0      6    22    29     2    60     7     1    38     1  
1      5     1     1    24     5   123    62    22     6  
2     11    15    55    40     5    10    20    73    19  
3      1     0     1    16     5    76    37     5     1  
4      8     9    11    26     2    28    51    17     4  
5      4    18    36     2     8     2     0    50     9  
6      0     3    12     1    18     0     0   101     0  
7     35    27    29     6    27     3     3    65     4  
8     20    29    34    22    26    61    44    71    42  
9     35    15    52    78    19    55    71    93    66  
10     3    33    45     3    20    14     4    32    13  
11     1     2     0    39     0    19    18    17    11  
12    24    20    57    23    33    11    12   425     9  
13     6     7    31  

In [47]:
# Display results
print("Confusion Matrix")
print(f"Accuracy Score: {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix
Accuracy Score: 0.7102306852306852
Classification Report
                                             precision    recall  f1-score   support

                         American Cream Ale       0.68      0.73      0.71      3651
                                 Barleywine       0.76      0.79      0.77      3689
                             Belgian Dubbel       0.67      0.80      0.73      3668
                   Belgian Quadrupel (Quad)       0.81      0.87      0.84      3638
                             Belgian Tripel       0.67      0.84      0.74      3584
                            Belgian Witbier       0.70      0.63      0.66      3683
                            Berliner Weisse       0.65      0.80      0.72      3681
                                 Blonde Ale       0.60      0.58      0.59      3685
                                  Brown Ale       0.67      0.57      0.61      3671
                                   Dark Ale       0.67      0.53      0.59 

In [48]:
# calculate feature importance in the Random Forest model
importances = xgb_model.feature_importances_
importances

array([0.189438  , 0.2811871 , 0.2896496 , 0.18110017, 0.05862512],
      dtype=float32)

In [49]:
# Sort the features by importances
sorted(zip(xgb_model.feature_importances_, encoded_df3.columns), reverse = True)

[(0.2896496, 'availability'),
 (0.2811871, 'style'),
 (0.189438, 'state_beer'),
 (0.18110017, 'abv'),
 (0.058625124, 'types')]

# Pruner for XGBoost

In [50]:
import numpy as np
import optuna
import sklearn.datasets
import sklearn.metrics
from sklearn.model_selection import train_test_split
import xgboost as xgb

In [73]:
# split training and testing data
y = encoded_df4["style"].values

X = encoded_df4.copy()
X = X.drop(columns =["style"])

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, random_state=1)


In [77]:
# normallize the data
from sklearn.preprocessing import MinMaxScaler

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)
X_valid_norm = norm.transform(X_valid)


In [78]:
X_train_norm

array([[0.9       , 0.83333333, 0.23076923, 0.33333333, 0.75      ],
       [0.72      , 0.33333333, 0.23076923, 0.26666667, 0.625     ],
       [0.74      , 1.        , 0.18181818, 0.33333333, 0.875     ],
       ...,
       [0.08      , 0.16666667, 0.17832168, 0.2       , 0.75      ],
       [0.38      , 1.        , 0.17132867, 0.66666667, 0.        ],
       [0.1       , 0.33333333, 0.14685315, 0.13333333, 0.6875    ]])

In [79]:
y_train

array([11, 13, 22, ...,  6, 14, 23])

In [80]:
# Object function
# ref: # (https://optuna.readthedocs.io/en/stable/faq.html#objective-func-additional-args).
def objective(trial):
    
    dtrain = xgb.DMatrix(X_train_norm, label = y_train)
    dvalid = xgb.DMatrix(X_valid_norm, label = y_valid)
    
    param = {
        "verbosity": 0,
        "objective": "binary:logistic",
        "booster": trial.suggest_categorical("booster", ["gbtree", "gblinear", "dart"]),
        "lambda": trial.suggest_float("lambda", 1e-8, 1.0, log=True),
        "alpha": trial.suggest_float("alpha", 1e-8, 1.0, log=True),
    }

    if param["booster"] in ["gbtree", "dart"]:
        param["max_depth"] = trial.suggest_int("max_depth", 3, 9, step=2)
        param["eta"] = trial.suggest_float("eta", 1e-8, 1.0, log=True)
        param["gamma"] = trial.suggest_float("gamma", 1e-8, 1.0, log=True)
        param["grow_policy"] = trial.suggest_categorical("grow_policy", ["depthwise", "lossguide"])
        
    if param["booster"] == "dart":
        param["sample_type"] = trial.suggest_categorical("sample_type", ["uniform", "weighted"])
        param["normalize_type"] = trial.suggest_categorical("normalize_type", ["tree", "forest"])
        param["rate_drop"] = trial.suggest_float("rate_drop", 1e-8, 1.0, log=True)
        param["skip_drop"] = trial.suggest_float("skip_drop", 1e-8, 1.0, log=True)
        
    # Add a callback for pruning
    
    bst = xgb.train(param, dtrain)
    preds = bst.predict(dvalid)
    pred_labels = np.rint(preds)
    accuracy = sklearn.metrics.accuracy_score(y_valid, pred_labels)
    return accuracy

In [81]:
# test
if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)

    print("Number of finished trials: ", len(study.trials))
    print("Best trial:")
    trial = study.best_trial

    print("  Value: {}".format(trial.value))
    print("  Params: ")

    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

[I 2022-06-03 14:36:50,591] A new study created in memory with name: no-name-a812b622-de26-4d63-bfad-d73e7142eff3
[W 2022-06-03 14:36:50,729] Trial 0 failed because of the following error: XGBoostError('[14:36:50] /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/objective/regression_obj.cu:120: label must be in [0,1] for logistic regression\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000121112364 dmlc::LogMessageFatal::~LogMessageFatal() + 116\n  [bt] (1) 2   libxgboost.dylib                    0x00000001212255d5 xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*) + 1557\n  [bt] (2) 3   libxgboost.dylib                    0x00000001211c05f4 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 612\n  [bt] (3) 4   libxgboost.dylib          

XGBoostError: [14:36:50] /Users/runner/miniforge3/conda-bld/xgboost-split_1645117948562/work/src/objective/regression_obj.cu:120: label must be in [0,1] for logistic regression
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x0000000121112364 dmlc::LogMessageFatal::~LogMessageFatal() + 116
  [bt] (1) 2   libxgboost.dylib                    0x00000001212255d5 xgboost::obj::RegLossObj<xgboost::obj::LogisticClassification>::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*) + 1557
  [bt] (2) 3   libxgboost.dylib                    0x00000001211c05f4 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 612
  [bt] (3) 4   libxgboost.dylib                    0x00000001211168f7 XGBoosterUpdateOneIter + 151
  [bt] (4) 5   libffi.7.dylib                      0x000000010ddb6ead ffi_call_unix64 + 85
  [bt] (5) 6   ???                                 0x00007ffee258a520 0x0 + 140732695880992



In [82]:
X_norm = norm.transform(X)
X_norm

array([[0.72      , 0.33333333, 0.16083916, 0.26666667, 0.875     ],
       [0.72      , 1.        , 0.18181818, 0.13333333, 0.875     ],
       [0.86      , 1.        , 0.17482517, 0.06666667, 0.75      ],
       ...,
       [0.08      , 0.33333333, 0.37062937, 0.66666667, 1.        ],
       [0.44      , 0.33333333, 0.44405594, 0.33333333, 0.9375    ],
       [0.3       , 1.        , 0.33566434, 0.06666667, 0.875     ]])

In [90]:
#try other codes

def objective(trial,data=X,target=y):
    
    train_x, test_x, train_y, test_y = train_test_split(data, target, test_size=0.33,random_state=1)
    
    norm = MinMaxScaler().fit(train_x)
    train_x_norm = norm.transform(train_x)
    test_x_norm = norm.transform(test_x)
    
    param = {
         
        'lambda': trial.suggest_loguniform('lambda', 1e-3, 10.0),
        'alpha': trial.suggest_loguniform('alpha', 1e-3, 10.0),
        'colsample_bytree': trial.suggest_categorical('colsample_bytree', [0.3,0.4,0.5,0.6,0.7,0.8,0.9, 1.0]),
        'subsample': trial.suggest_categorical('subsample', [0.4,0.5,0.6,0.7,0.8,1.0]),
        'learning_rate': trial.suggest_categorical('learning_rate', [0.008,0.01,0.012,0.014,0.016,0.018, 0.02]),
        'n_estimators': 10000,
        'max_depth': trial.suggest_categorical('max_depth', [5,7,9,11,13,15,17]),
        'random_state': trial.suggest_categorical('random_state', [2020]),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 300),
    }
    model = xgb.XGBClassifier(**param)  
    
    model.fit(train_x_norm,train_y,eval_set=[(test_x_norm,test_y)],early_stopping_rounds=100,verbose=False)
    
    preds = model.predict(test_x_norm)
    
    accuracy = sklearn.metrics.accuracy_score(test_y, preds)
    
    return accuracy
    

In [ ]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)
print('Number of finished trials:', len(study.trials))
print('Best trial:', study.best_trial.params)

[I 2022-06-03 15:00:39,404] A new study created in memory with name: no-name-32d9e56b-e357-4cd5-9f4d-c586e5d56c59
/Users/alexzzf/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
